### ISSUE TITLE
"E121: Undefined variable: b:dirvish" error when switching to Dirvish directory buffer

### ISSUE THREAD

**Issue by deathlyfrantic** [justinmk/vim-dirvish#136]
I'm getting this error:
```
Error detected while processing function <SNR>88_on_bufenter:
line    2:
E121: Undefined variable: b:dirvish
E116: Invalid arguments for function extend
E15: Invalid expression: extend(get(w:, 'dirvish', {}), b:dirvish, 'keep')
```

To reproduce:
1. start nvim
2. `:e <a directory>`
3. `:enew` or `:e <a file>`
4. `:b1`

It seems to be coming from here: https://github.com/justinmk/vim-dirvish/blob/d33796c460229b2cf0dd09fedf1b272da9d13a42/autoload/dirvish.vim#L161

I am guessing maybe this has something to do with not setting `nobuflisted` if there is only one buffer? https://github.com/justinmk/vim-dirvish/blob/d33796c460229b2cf0dd09fedf1b272da9d13a42/autoload/dirvish.vim#L396-L398 If there is more than one buffer open, `nobuflisted` is set and I'm not able to switch back to the Dirvish buffer open to the directory, which prevents this problem from happening.

This is not a huge error - I only discovered it because I accidentally edited a directory rather than a file, but I wanted to report it since I can reproduce it reliably.

**Comment by justinmk** [comment]
cannot reproduce. I tried this:

    nvim -u NORC +":set runtimepath+=~/.config/nvim/pack/minpac/start/vim-dirvish/plugin/dirvish.vim" +":runtime plugin/dirvish.vim"

Can you try that also (replace the path as appropriate for your system)? Maybe there's a setting that affects this.

Dirvish already takes steps to avoid problems with buffer 1.

**Comment by deathlyfrantic** [comment]
With that setup I cannot reproduce it either. With my normal setup I still can, so I have some other conflict. Any suggestions on what to look for?

**Comment by deathlyfrantic** [comment]
I've narrowed it down to this bit I have in my init.vim:

```vim
  autocmd BufEnter *
        \ if winnr('$') == 1 && (&bt == 'quickfix' || &ft == 'dirvish') |
        \   if len(filter(getbufinfo(), {_, b -> b.listed})) == 1 |
        \     quit |
        \   else |
        \     bd! |
        \   endif |
        \ endif
```

The intent of this chunk is to close a quickfix or dirvish window when I close out the "associated" window, or quit Vim entirely when a quickfix or dirvish window is the last window open. When I comment this out this error goes away, so clearly there's some interaction here that throws a wrench in the works. I've done a ton of autocmd logging trying to figure out the sequence of events that is causing this but I'm not having much luck. Since this seems to be specific to my setup, and it's something I almost never come across in my normal workflows, I don't mind if you close out this issue.

**Comment by justinmk** [comment]
I tried this but still couldn't reproduce:

```
:set hidden
:e <a directory>
:enew or :e <a file>
:bdelete! #
:b1
```

However, I pushed a potential fix. Can you try it?

**Comment by deathlyfrantic** [comment]
Your new example (with `bdelete! #`) works fine for me, but with my janky autocmd it's still broken, albeit with a different error:

```
Error detected while processing function <SNR>78_on_bufenter:
line    2:
E499: Empty file name for '%' or '#', only works with ":p:h":     Dirvish %
```

This must be because I'm doing a `bdelete` in a `BufEnter` event which I'm sure is not recommended.

**Comment by justinmk** [comment]
> This must be because I'm doing a `bdelete` in a `BufEnter` event which I'm sure is not recommended.

Heh, that's technically true, and is a never-ending source of segfaults in Vim itself.

Actually, Vim/Nvim should really stop processing autocmds on a buffer once the buffer is deleted ...

A plugin can't really detect the situation, the following returns `1`:

     au BufEnter BACKERS* bd!|echom bufexists(bufnr('%'))

I suppose `s:on_bufenter()` could just return early if the filename is empty.

**Comment by deathlyfrantic** [comment]
The latest commit solves it! Interestingly now that the error isn't happening, my autocmd completes and closes the Dirvish buffer, so `:b1` actually just closes the Dirvish buffer without changing which one I'm in.

Thanks for fixing this despite being such an esoteric issue!
